server:
  port: 8443
  ssl:
    key-store: classpath:mykeys.jks
    key-store-password: tacocloud
    key-password: tacocloud


#spring:
#  datasource:
#    url: jdbc:mysql://localhost/tacocloud
#    username: tacodb
#    password: tacopassword
#    driver-class-name: com.mysql.jdbc.Driver
#    schema:
#      - order-schema.sql
#      - ingredient-schema.sql
#    data:
#      - ingredients.sql